services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "no"
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: restaurante
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - rede_prova

volumes:
  mysql_data:

networks:
  rede_prova:
    external: true